#ifndef CONSTDEFINITIONS_H
#define CONSTDEFINITIONS_H

#define INTEGRITY_MAX       100.0f
#define INTEGRITY_MIN       0.0f

#define STRENGTH_LEVEL_1    100
#define STRENGTH_LEVEL_2    125
#define STRENGTH_LEVEL_3    150
#define STRENGTH_LEVEL_4    200

#define UPGRADECOST_LEVEL_2 50
#define UPGRADECOST_LEVEL_3 200
#define UPGRADECOST_LEVEL_4 500

#define REPAIRCOST_LEVEL_1  25
#define REPAIRCOST_LEVEL_2  50
#define REPAIRCOST_LEVEL_3  75
#define REPAIRCOST_LEVEL_4  125

#endif // !CONSTDEFINITIONS_H